### ISSUE TITLE
is :date_time value being calculated correctly

### ISSUE THREAD

**Issue by ikbenben** [richardbrodie/fitreader#2]
The code is doing some data manipulation `Message#process_value` however it looks like the calculated for :date_time type is not being calculated correctly as the result of the `Time.at(val + t).utc` is not being assigned to `val` like the other statements. 

```
  def process_value(type, val)
    if type[:type][0..3].to_sym == :enum
      val = Sdk.enum(type[:type])[val]
    elsif type[:type] == :date_time
      t = Time.new(1989, 12, 31, 0, 0, 0, '+00:00').utc.to_i
      Time.at(val + t).utc
    elsif type[:type] == :local_date_time
      t = Time.new(1989, 12, 31, 0, 0, 0, '+02:00').utc.to_i
      val = Time.at(val + t)
    elsif type[:type] == :coordinates
      val *= (180.0 / 2**31)
    end
```

This may be expected behaviour but just want to confirm

**Comment by richardbrodie** [comment]
Hmm, this appears to be a typo. I suspect it might be because the FIT files I was using to validate were perhaps always using `:local_date_time`.

**Comment by ikbenben** [comment]
Does this mean you will change it so it does do the conversion? I need the :start_time value from a session message which is a :date_time field type. I can submit a PR instead if you would like.

However, I also need access to the raw value. Is there a way to grab the raw values (ie before any conversions) of a message? 

As an example of why I need the raw :start_time is that a FIT file may have multiple session messages indicating different workouts. We need to find all laps or record messages that occurred during a given session. To do this, we need to take the raw :start_time and the :total_elapsed_time value from the session and find any laps / records whose start time is between :start_time and (:start_time + :total_elapsed_time)

I can of course convert the UTC Datetime back to the raw value but may be easier to just grab the raw value before any conversion

**Comment by richardbrodie** [comment]
I'll change it simply so it does the conversion for now, but I will also look into adding some sort of `#raw_val` field as well. 

I did in fact provide both values in an earlier version, but mostly for debugging purposes. I took it out when I switched to producing simple `{field_name: value}` hashes instead of using the `DataField` itself.

The problem here is maintaining backwards compatibility so that the resulting `Message` data fields are still directly usable by anyone who expects `{field_name: value}`.

**Comment by ikbenben** [comment]
The more I'm working with the gem, the more I think the raw value is more beneficial than having the converted date time. Making the :date_time convert to be a Time type means even the :timestamp field becomes a value of type Time. Not sure it makes much difference as you can still do time arithmetic but working in seconds seems more natural

**Comment by richardbrodie** [comment]
Yes, I think you're probably right. My feeling these days is that gems such as this should be pretty unopinionated about most things and leave it up to the user to be more specific when needs be. 

It's better to process things to a sensible generic value.
